--liquibase formatted sql
--liquibase formatted sql

--changeset Vladislav Skibin:000000-create-enums
create type status as enum('BACKLOG', 'IN_PROGRESS', 'DONE');
create type type as enum('BUG', 'FEATURE');
create type role as enum('ADMIN', 'MANAGER', 'PROGRAMMER');

--changeset Vladislav Skibin:000001-create-table-users
create table users
(
    id          int8 generated by default as identity primary key,
    username    varchar(64)  not null,
    password    varchar(64)  not null,
    first_name  varchar(64)  not null,
    second_name varchar(64)  not null,
    email       varchar(255) not null,
    user_role   role         not null,
    project_id  int8
);

--changeset Vladislav Skibin:000002-create-table-project
create table project
(
    id                  int8 generated by default as identity primary key,
    project_name        varchar(255) not null,
    project_description varchar(255),
    project_start_date  date,
    project_end_date    date,
    project_status      status       not null,
    owner_id            int8         not null
);

--changeset Vladislav Skibin:000003-create-table-task

create table task
(
    id               int8 generated by default as identity primary key,
    task_name        varchar(255) not null,
    task_description varchar(255),
    task_created_at  timestamp    not null,
    task_updated_at  timestamp    not null,
    task_status      status       not null,
    task_type        type         not null,
    task_start_date  date,
    task_end_date    date,
    assigner_id      int8,
    owner_id         int8         not null,
    project_id       int8         not null,
    release_id       int8
);

--changeset Vladislav Skibin:000004-create-table-release

create table release
(
    id                  int8 generated by default as identity primary key,
    release_version     varchar(128) not null,
    release_description varchar(255),
    release_end_date    date,
    release_start_date  date
);

--changeset Vladislav Skibin:000005-add-foreign-key-constraints

alter table project
    add constraint FK_owner
        foreign key (owner_id)
            references users (id)
            on delete restrict
            on update cascade;
alter table task
    add constraint FK_assigner
        foreign key (assigner_id)
            references users (id)
            on delete set null
            on update cascade;
alter table task
    add constraint FK_owner
        foreign key (owner_id)
            references users (id)
            on delete cascade
            on update cascade;
alter table task
    add constraint FK_project
        foreign key (project_id)
            references project (id)
            on delete restrict
            on update cascade;
alter table task
    add constraint FK_release
        foreign key (release_id)
            references release (id)
            on delete restrict
            on update cascade;
alter table users
    add constraint FK_project
        foreign key (project_id)
            references project (id)
            on delete set null
            on update cascade;